Disable two more coreutils tests.
These two tests that fail are corner cases. The failing test in install/basic-1
tries whether ginstall works from an unreadable directory with an inaccessible
parent. Because sydbox can't access those directories, it denies the system
calls with EPERM thus the test fails.
The other failing test in mkdir/p-3 fails with the same reason as well.

See bug204 for more information.

Signed-off-by: Ali Polatel <polatel@gmail.com>

diff --git a/packages/sys-apps/coreutils/files/coreutils-7.4-sydbox.patch b/packages/sys-apps/coreutils/files/coreutils-7.4-sydbox.patch
--- a/packages/sys-apps/coreutils/files/coreutils-7.4-sydbox.patch
+++ b/packages/sys-apps/coreutils/files/coreutils-7.4-sydbox.patch
@@ -62,3 +62,53 @@ diff -ur coreutils-7.4/tests/touch/fail-diag coreutils-7.4-sydbox/tests/touch/fa
  d1=no-$$
  dir=/$d1/such-dir
  # Ensure that $d1 doesn't already exist.
+diff -ur coreutils-7.4/tests/install/basic-1 coreutils-7.4-sydbox/tests/install/basic-1
+--- coreutils-7.4/tests/install/basic-1	2009-02-27 18:36:00.000000000 +0200
++++ coreutils-7.4-sydbox/tests/install/basic-1	2009-08-16 18:54:49.000000000 +0300
+@@ -106,15 +106,16 @@
+ # inaccessible parent.  coreutils 5.97 fails this test.
+ # Perform this test only if "." is on a local file system.
+ # Otherwise, it would fail e.g., on an NFS-mounted file system.
+-if df --local . >/dev/null 2>&1; then
+-  mkdir -p sub1/d || fail=1
+-  (cd sub1/d && chmod a-r . && chmod a-rx .. &&
+-   ginstall -d "$iwd/xx/zz" rel/a rel/b) || fail=1
+-  chmod 755 sub1 sub1/d || fail=1
+-  test -d xx/zz || fail=1
+-  test -d sub1/d/rel/a || fail=1
+-  test -d sub1/d/rel/b || fail=1
+-fi
++# XXX: This test fails with sydbox as well, see my comment in bug 204. -alip
++#if df --local . >/dev/null 2>&1; then
++#  mkdir -p sub1/d || fail=1
++#  (cd sub1/d && chmod a-r . && chmod a-rx .. &&
++#   ginstall -d "$iwd/xx/zz" rel/a rel/b) || fail=1
++#  chmod 755 sub1 sub1/d || fail=1
++#  test -d xx/zz || fail=1
++#  test -d sub1/d/rel/a || fail=1
++#  test -d sub1/d/rel/b || fail=1
++#fi
+ 
+ touch file || fail=1
+ ginstall -Dv file sub3/a/b/c/file >out 2>&1 || fail=1
+diff -ur coreutils-7.4/tests/mkdir/p-3 coreutils-7.4-sydbox/tests/mkdir/p-3
+--- coreutils-7.4/tests/mkdir/p-3	2009-02-27 18:36:01.000000000 +0200
++++ coreutils-7.4-sydbox/tests/mkdir/p-3	2009-08-16 18:55:21.000000000 +0300
+@@ -42,11 +42,12 @@
+ # whose parent is inaccessible.  coreutils 5.97 fails this test.
+ # Perform this test only if "." is on a local file system.
+ # Otherwise, it would fail e.g., on an NFS-mounted file system.
+-if df --local . >/dev/null 2>&1; then
+-  (cd no-acce3s/d && chmod a-r . && chmod a-rx .. &&
+-      mkdir -p a/b "$p/b/c" d/e && test -d a/b && test -d d/e) || fail=1
+-  test -d "$p/b/c" || fail=1
+-fi
++# XXX: This test fails with sydbox as well, see my comment in bug 204. -alip
++#if df --local . >/dev/null 2>&1; then
++#  (cd no-acce3s/d && chmod a-r . && chmod a-rx .. &&
++#      mkdir -p a/b "$p/b/c" d/e && test -d a/b && test -d d/e) || fail=1
++#  test -d "$p/b/c" || fail=1
++#fi
+ 
+ b=`ls "$p/a" | tr -d '\n'`
+ # With coreutils-5.3.0, this would fail with $b=bu.
